_format_version: "2.1"
_transform: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS

services:
  - name: example-service
    url: https://mockbin.org
    routes:
      - name: public-route
        paths:
          - /api
          
  - name: auth-service
    url: http://auth-service.default.svc.cluster.local:8100 # untuk kubernetes
    # url: http://auth-service:8100
    routes:
      - name: auth-route
        paths:
          - /api/auth
        strip_path: false
        preserve_host: false

  - name: express-service
    url: http://express-service.default.svc.cluster.local:8001 # untuk kubernetes
    # url: http://express-service:8001
    plugins:
      - name: auth
    routes:
      - name: express-route
        paths:
          - /api/express
        strip_path: false
        preserve_host: false
  
  - name: hono-service
    url: http://hono-service.default.svc.cluster.local:8002 # untuk kubernetes
    # url: http://hono-service:8002
    plugins:
      - name: auth
    routes:
      - name: hono-route
        paths:
          - /api/hono
        strip_path: false
        preserve_host: false

  - name: elysia-service
    url: http://elysia-service.default.svc.cluster.local:8003 # untuk kubernetes
    # url: http://elysia-service:8003
    plugins:
      - name: auth
    routes:
      - name: elysia-route
        paths:
          - /api/elysia
        strip_path: false
        preserve_host: false

  - name: fastify-service
    url: http://fastify-service.default.svc.cluster.local:8004 # untuk kubernetes
    # url: http://fastify-service:8004
    plugins:
      - name: auth
    routes:
      - name: fastify-route
        paths:
          - /api/fastify
        strip_path: false
        preserve_host: false

  - name: koa-service
    url: http://koa-service.default.svc.cluster.local:8005 # untuk kubernetes
    # url: http://koa-service:8005
    plugins:
      - name: auth
    routes:
      - name: koa-route
        paths:
          - /api/koa
        strip_path: false
        preserve_host: false