apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bun-auth-api
  template:
    metadata:
      labels:
        app: bun-auth-api
    spec:
      containers:
        - name: bun-auth-api
          image: ghcr.io/rickyfirmansyah27/auth-service:20241126134226
          env:
            - name: JWT_SECRET
              value: "qwqonddqwiqwh1821j31igbwiduxhn8112ex1h299qhwehq98u"
            - name: PORT
              value: "8100"
            - name: DB_HOST
              value: db.ewpvmtfpdvvldyrhksic.supabase.co
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: myapp
            - name: DB_SSL
              value: "true"
            - name: LOGTAIL_API_KEY
              value: "qLeeazh2QzV47U2f7EnoMhT8"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bun-auth-api
spec:
  selector:
    app: bun-auth-api
  ports:
    - port: 8100
      targetPort: 8100

