apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-elysia-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bun-elysia-api
  template:
    metadata:
      labels:
        app: bun-elysia-api
    spec:
      containers:
        - name: bun-elysia-api
          image: ghcr.io/rickyfirmansyah27/elysia-service:20241127121445
          env:
            - name: JWT_SECRET
              value: qwqonddqwiqwh1821j31igbwiduxhn8112ex1h299qhwehq98u
            - name: PORT
              value: "8003"
            - name: DATABASE_URL
              value: postgresql://myapp_owner:MQuO3eoA6Lik@ep-steep-wave-a12ap90f-pooler.ap-southeast-1.aws.neon.tech/myapp?sslmode=require
            - name: LOGTAIL_API_KEY
              value: qLeeazh2QzV47U2f7EnoMhT8
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bun-elysia-api
spec:
  selector:
    app: bun-elysia-api
  ports:
    - port: 8003
      targetPort: 8003
