apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bun-data-api
  template:
    metadata:
      labels:
        app: bun-data-api
    spec:
      containers:
        - name: bun-data-api
          image: ghcr.io/rickyfirmansyah27/express-service:20241125041846
          env:
            - name: JWT_SECRET
              value: "qwqonddqwiqwh1821j31igbwiduxhn8112ex1h299qhwehq98u"
            - name: PORT
              value: "8001"
            - name: DB_HOST
              value: db.ewpvmtfpdvvldyrhksic.supabase.co
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: myapp
            - name: DB_SSL
              value: "true"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bun-data-api
spec:
  selector:
    app: bun-data-api
  ports:
    - port: 8001
      targetPort: 8001

