apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastify-service
  template:
    metadata:
      labels:
        app: fastify-service
    spec:
      containers:
        - name: fastify-service
          image: ghcr.io/rickyfirmansyah27/fastify-service:20250104031633
          env:
            - name: JWT_SECRET
              value: qwqonddqwiqwh1821j31igbwiduxhn8112ex1h299qhwehq98u
            - name: PORT
              value: "8004"
            - name: DATABASE_URL
              value: postgresql://myapp_owner:MQuO3eoA6Lik@ep-steep-wave-a12ap90f-pooler.ap-southeast-1.aws.neon.tech/myapp?sslmode=require
            - name: LOGTAIL_API_KEY
              value: qLeeazh2QzV47U2f7EnoMhT8
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-service
spec:
  selector:
    app: fastify-service
  ports:
    - port: 8004
      targetPort: 8004
