name: Docker Image Auth Service

on:
  push:
    branches:
      - "main"
    paths:
      - 'apps/auth-service/**'

jobs:
  build_and_publish_auth_service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: RickyFirmansyah27
          password: ${{ secrets.GH_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine the next version
        id: version
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/auth-service/Dockerfile
          push: true
          tags: ghcr.io/rickyfirmansyah27/auth-service:${{ steps.version.outputs.date }}
