name: Docker Image Hono Service

on:
  push:
    branches:
      - "main"
    paths:
      - 'apps/hono-service/**'

jobs:
  build_and_publish_hono_service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: RickyFirmansyah27
          password: ${{ secrets.GH_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine the next version
        id: version
        run: |
          echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/hono-service/Dockerfile
          push: true
          tags: ghcr.io/rickyfirmansyah27/hono-service:${{ env.date }}
